### ISSUE TITLE
Can't install NPU dkms, build fails

### ISSUE THREAD

**Issue by segabor** [Sky1-Linux/sky1-drivers-dkms#2]
installation of `sky1-npu-dkms` fails during build phase. Some headers are not found (but they are actually there).

Platform: Orion O6
OS: Debian GNU/Linux forky/sid
uname: Linux orion 6.18.4-sky1 #1 SMP PREEMPT Wed Jan 14 21:15:58 AEDT 2026 aarch64 GNU/Linux

# Installation error

```
Building initial module sky1-npu/1.0.0 for 6.18.4-sky1
The kernel is built without module signing facility, modules won't be signed

Building module(s)...(bad exit status: 2)
Failed command:
make -j12 KERNELRELEASE=6.18.4-sky1 -C /lib/modules/6.18.4-sky1/build M=/var/lib/dkms/sky1-npu/1.0.0/build

Error! Bad return status for module build on kernel: 6.18.4-sky1 (aarch64)
Consult /var/lib/dkms/sky1-npu/1.0.0/build/make.log for more information.
dpkg: error processing package sky1-npu-dkms (--configure):
 old sky1-npu-dkms package postinst maintainer script subprocess failed with exit status 10
Errors were encountered while processing:
 sky1-npu-dkms
```

# Build error
```
DKMS (dkms-3.2.2) make.log for sky1-npu/1.0.0 for kernel 6.18.4-sky1 (aarch64)
2026. jan. 21., szerda, 21:38:05 CET

Building module(s)
# command: make -j12 KERNELRELEASE=6.18.4-sky1 -C /lib/modules/6.18.4-sky1/build M=/var/lib/dkms/sky1-npu/1.0.0/build
make: Entering directory '/usr/src/linux-headers-6.18.4-sky1'
make[1]: Entering directory '/var/lib/dkms/sky1-npu/1.0.0/build'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Debian 15.2.0-11) 15.2.0
  You are using:           gcc (Debian 15.2.0-12) 15.2.0
  CC      armchina-npu/default/default.o
  CC      armchina-npu/aipu.o
  CC      armchina-npu/aipu_common.o
  CC      armchina-npu/aipu_irq.o
  CC      armchina-npu/aipu_io.o
  CC      armchina-npu/aipu_job_manager.o
  CC      armchina-npu/aipu_dma_buf.o
  CC      armchina-npu/aipu_mm.o
  CC      armchina-npu/aipu_priv.o
  CC      armchina-npu/aipu_tcb.o
  CC      armchina-npu/zhouyi/zhouyi.o
  CC      armchina-npu/zhouyi/v1.o
armchina-npu/zhouyi/v1.c:6:10: fatal error: aipu_priv.h: No such file or directory
    6 | #include "aipu_priv.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.18.4-sky1/scripts/Makefile.build:287: armchina-npu/zhouyi/v1.o] Error 1
make[3]: *** Waiting for unfinished jobs....
armchina-npu/default/default.c:11:10: fatal error: armchina_aipu_soc.h: No such file or directory
   11 | #include "armchina_aipu_soc.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.18.4-sky1/scripts/Makefile.build:287: armchina-npu/default/default.o] Error 1
In file included from armchina-npu/aipu_job_manager.c:10:
armchina-npu/aipu_job_manager.h:12:10: fatal error: armchina_aipu.h: No such file or directory
   12 | #include <armchina_aipu.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.18.4-sky1/scripts/Makefile.build:287: armchina-npu/aipu_job_manager.o] Error 1
armchina-npu/aipu.c:14:10: fatal error: armchina_aipu.h: No such file or directory
   14 | #include <armchina_aipu.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.18.4-sky1/scripts/Makefile.build:287: armchina-npu/aipu.o] Error 1
In file included from armchina-npu/aipu_irq.c:8:
armchina-npu/aipu_partition.h:11:10: fatal error: armchina_aipu.h: No such file or directory
   11 | #include <armchina_aipu.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.18.4-sky1/scripts/Makefile.build:287: armchina-npu/aipu_irq.o] Error 1
In file included from armchina-npu/zhouyi/zhouyi.c:6:
armchina-npu/zhouyi/zhouyi.h:9:10: fatal error: armchina_aipu.h: No such file or directory
    9 | #include <armchina_aipu.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.18.4-sky1/scripts/Makefile.build:287: armchina-npu/zhouyi/zhouyi.o] Error 1
In file included from armchina-npu/aipu_tcb.c:5:
armchina-npu/aipu_mm.h:11:10: fatal error: armchina_aipu.h: No such file or directory
   11 | #include <armchina_aipu.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.18.4-sky1/scripts/Makefile.build:287: armchina-npu/aipu_tcb.o] Error 1
In file included from armchina-npu/aipu_priv.c:6:
armchina-npu/aipu_priv.h:11:10: fatal error: armchina_aipu_soc.h: No such file or directory
   11 | #include "armchina_aipu_soc.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.18.4-sky1/scripts/Makefile.build:287: armchina-npu/aipu_priv.o] Error 1
In file included from armchina-npu/aipu_dma_buf.c:6:
armchina-npu/aipu_dma_buf.h:9:10: fatal error: armchina_aipu.h: No such file or directory
    9 | #include "armchina_aipu.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.18.4-sky1/scripts/Makefile.build:287: armchina-npu/aipu_dma_buf.o] Error 1
In file included from armchina-npu/aipu_common.h:7,
                 from armchina-npu/aipu_common.c:7:
armchina-npu/aipu_priv.h:11:10: fatal error: armchina_aipu_soc.h: No such file or directory
   11 | #include "armchina_aipu_soc.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.18.4-sky1/scripts/Makefile.build:287: armchina-npu/aipu_common.o] Error 1
In file included from armchina-npu/aipu_mm.c:22:
armchina-npu/aipu_priv.h:11:10: fatal error: armchina_aipu_soc.h: No such file or directory
   11 | #include "armchina_aipu_soc.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.18.4-sky1/scripts/Makefile.build:287: armchina-npu/aipu_mm.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.18.4-sky1/Makefile:2010: .] Error 2
make[1]: *** [/usr/src/linux-headers-6.18.4-sky1/Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/sky1-npu/1.0.0/build'
make: *** [Makefile:248: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.18.4-sky1'
```
